### ISSUE TITLE
WIP: Unit vs Integration - where is the line

### ISSUE THREAD

**Issue by codebryo** [expect-Exception/expect-exception#6]
- Go through the definitions of unit and integration testing
- The challenge with modern UI libraries (Vue, React, Angular, ...) where does unit testing end and integration testing start
- Talk about common pitfalls in unit testing and modern libraries. e.g. Don't test the library/framework
- mount vs shallowMount

**Comment by Vannsl** [comment]
This is not the answer you're looking for, but an interesting comparison:

What We Can Learn About Testing From The Wheel - Kent C. Dodds (Ignite Fluent 2016)
https://www.youtube.com/watch?v=Da9wfQ0frGA&feature=youtu.be

I have the exact same question about `mount` vs `shallowMount`. I always argued that mounting would be an integration test already. But that wasn't helpful all of the time. I decided something for myself:

- if a component is actually a standalone component, I unit test the whole thing separated from everything else and I don't make mount tests in parent components.
- if I split a component in smaller pieces just for the sake of readability, it may be only a "full component" when combined. Then I use `mount` and don't care if the components come from different files.

Was that understandable?
